version: '2.0'

services:
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'typo3'
      MYSQL_USER: 'typo3'
      MYSQL_PASSWORD: 'password'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  typo3dev:
    image: php:7.0-apache
    volumes:
      - './setup/:/setup'
      - './src/:/src'
    ports:
      - '81:80'
    links:
      - mariadb:db
    depends_on:
      - mariadb
    command: bash -c '/setup/setup.sh && apache2-foreground'
    environment:
      TYPO3_CONTEXT: 'Development'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    depends_on:
      - mariadb
    ports:
      - '8085:80'
    environment:
      PMA_ARBITRARY: 0